name: Lint, Build & Test Docker images

on:
  push:
    branches: [ main ]
  

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
    - name:  Checkout code
      uses: actions/checkout@v3

    # Lint Dockerfiles for practices & mistakes
    - name:  Lint backend Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./backend/Dockerfile

    - name:  Lint frontend Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./frontend/Dockerfile

    #  Set up Docker Buildx for modern multi-platform builds
    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #  Build backend Docker image
    - name:  Build backend image
      run: docker build -t my-backend:latest ./backend

    #  Build frontend Docker image
    - name:  Build frontend image
      run: docker build -t my-frontend:latest ./frontend

    #  Test: Run backend container and check it responds
    - name:  Run backend container & check health
      run: |
        docker run -d -p 5000:5000 --name test-backend my-backend:latest
        sleep 5
        curl --fail http://localhost:5000/health || (docker logs test-backend && exit 1)
        docker stop test-backend && docker rm test-backend

    # Test: Run frontend container and check it serves index.html
    - name:  Run frontend container & check page
      run: |
        docker run -d -p 8080:80 --name test-frontend my-frontend:latest
        sleep 5
        curl --fail http://localhost:8080 || (docker logs test-frontend && exit 1)
        docker stop test-frontend && docker rm test-frontend
